// GENERATED FILE -- DO NOT EDIT.
//
// Produced by tools/gen_disk_layouts.nim from
// repro/disk_layouts.nim, which is the single declaration of
// which disk layouts ReproOS ships and what documents they
// render to. Regenerate with:
//
//     nim r tools/gen_disk_layouts.nim
//
// Editing this file by hand re-creates the divergence it was
// introduced to remove: the installer used to render its own
// disko JSON, and that copy disagreed with the one the image
// build applied. tests/test_installer_disk_layout_parity.nim
// re-derives this file and fails if it differs by a byte.

#pragma once

namespace reproos {
namespace generated {

// One registered layout preset. `documentTemplate` and
// `hardwareTemplate` are the rendered documents with the three
// per-install parameters left as placeholders; the C++ side
// substitutes, it does not render.
struct DiskLayoutPreset {
    const char *name;
    const char *summary;
    bool buildable;
    const char *unbuildableReason;
    int minDiskSizeGb;
    int defaultEspSizeMib;
    const char *documentTemplate;
    const char *hardwareTemplate;
};

inline constexpr const char *IdPlaceholder = "@REPROOS_ID@";
inline constexpr const char *DevicePlaceholder = "@REPROOS_DEVICE@";
inline constexpr const char *EspMibPlaceholder = "@REPROOS_ESP_MIB@";

inline constexpr const char *DefaultDiskLayoutName = "uefi-ext4";
inline constexpr int DefaultDiskSizeGb = 8;
inline constexpr int DefaultEspSizeMib = 512;
inline constexpr int MinEspSizeMib = 128;

// The listing every "unknown layout" refusal prints, rendered
// by repro/disk_layouts.nim's legalDiskLayoutListing().
inline constexpr const char *LegalDiskLayoutListing =
    R"REPROOS_LAYOUT(    uefi-ext4 — ESP + a single writable ext4 root; the layout every ReproOS image has shipped with
    uefi-attested — ESP + two integrity-checked read-only root slots + separate /var, /home and swap; the shape an attestable image needs (declared, not yet buildable))REPROOS_LAYOUT";

inline constexpr DiskLayoutPreset DiskLayoutPresets[] = {
    {
        /* name */ "uefi-ext4",
        /* summary */ "ESP + a single writable ext4 root; the layout every ReproOS image has shipped with",
        /* buildable */ true,
        /* unbuildableReason */ "",
        /* minDiskSizeGb */ 4,
        /* defaultEspSizeMib */ 512,
        /* documentTemplate */
        R"REPROOS_LAYOUT({
  "id": "@REPROOS_ID@",
  "cpuArch": "x86_64",
  "cpuMicrocode": "intel",
  "kernelModules": [],
  "loaderDevice": "@REPROOS_DEVICE@",
  "filesystems": [],
  "graphicsDrivers": [],
  "audioCards": [],
  "disko": {
    "disks": {
      "main": {
        "device": "@REPROOS_DEVICE@",
        "type": "gpt",
        "partitions": {
          "esp": {
            "type": "esp",
            "size": "@REPROOS_ESP_MIB@M",
            "bootable": true,
            "content": {
              "kind": "filesystem",
              "format": "vfat",
              "mountpoint": "/boot",
              "mountOptions": ["umask=0077"],
              "label": "ESP",
              "subvols": []
            }
          },
          "root": {
            "type": "linux",
            "size": "100%",
            "bootable": false,
            "content": {
              "kind": "filesystem",
              "format": "ext4",
              "mountpoint": "/",
              "mountOptions": ["defaults"],
              "label": "reproos-root",
              "subvols": []
            }
          }
        }
      }
    },
    "pools": []
  }
}
)REPROOS_LAYOUT",
        /* hardwareTemplate */
        R"REPROOS_LAYOUT(# /etc/repro/hardware.nim --- generated by the ReproOS installer
import repro_profile

hardware "@REPROOS_ID@":
  cpu:
    arch: "x86_64"
    microcode: "intel"
  boot:
    loaderDevice: "@REPROOS_DEVICE@"
  disko:
    disks:
      "main":
        device: "@REPROOS_DEVICE@"
        table: "gpt"
        partitions:
          "esp":
            kind: "esp"
            size: "@REPROOS_ESP_MIB@M"
            bootable: true
            content:
              filesystem:
                format: "vfat"
                mountpoint: "/boot"
                mountOptions: @["umask=0077"]
                label: "ESP"
          "root":
            kind: "linux"
            size: "100%"
            bootable: false
            content:
              filesystem:
                format: "ext4"
                mountpoint: "/"
                mountOptions: @["defaults"]
                label: "reproos-root"
)REPROOS_LAYOUT",
    },
    {
        /* name */ "uefi-attested",
        /* summary */ "ESP + two integrity-checked read-only root slots + separate /var, /home and swap; the shape an attestable image needs",
        /* buildable */ false,
        /* unbuildableReason */ "boot goes through a unified kernel image whose command line pins the root hash inside the measured binary; this layout carries both root slots and both hash-tree volumes that command line names, the image driver writes the integrity-checked root and its hash tree onto them and re-verifies the pair where it landed, the root is now configured — hostname, fstab, accounts, services, desktop — before that hash is taken rather than after the install, and a write-capable mount of a hashed carrier is refused rather than merely avoided, and the guest inode policy is now carried INTO the root image as that image is made — root-owned inodes, a setuid /usr/bin/sudo, an unwritable /etc/sudoers — with an image that does not carry it refused rather than hashed. What is still missing is the WRITABLE STATE this layout separates out. /var and /home are their own volumes, the apply creates them empty, and the initramfs mounts them over the measured root at first boot — so the configured user's home and /var/lib content are shadowed by empty filesystems the moment the machine starts, and the account the installer configured has nowhere to log in to. Nothing seeds them yet. Until something does, an image built from this layout would boot, verify against its own root hash, and have no usable session",
        /* minDiskSizeGb */ 20,
        /* defaultEspSizeMib */ 512,
        /* documentTemplate */
        R"REPROOS_LAYOUT({
  "id": "@REPROOS_ID@",
  "cpuArch": "x86_64",
  "cpuMicrocode": "intel",
  "kernelModules": [],
  "loaderDevice": "@REPROOS_DEVICE@",
  "filesystems": [],
  "graphicsDrivers": [],
  "audioCards": [],
  "disko": {
    "disks": {
      "main": {
        "device": "@REPROOS_DEVICE@",
        "type": "gpt",
        "partitions": {
          "esp": {
            "type": "esp",
            "size": "@REPROOS_ESP_MIB@M",
            "bootable": true,
            "content": {
              "kind": "filesystem",
              "format": "vfat",
              "mountpoint": "/boot",
              "mountOptions": ["umask=0077"],
              "label": "ESP",
              "subvols": []
            }
          },
          "root-a": {
            "type": "linux",
            "size": "4G",
            "bootable": false,
            "content": {
              "kind": "none"
            }
          },
          "roothash-a": {
            "type": "linux",
            "size": "64M",
            "bootable": false,
            "content": {
              "kind": "none"
            }
          },
          "root-b": {
            "type": "linux",
            "size": "4G",
            "bootable": false,
            "content": {
              "kind": "none"
            }
          },
          "roothash-b": {
            "type": "linux",
            "size": "64M",
            "bootable": false,
            "content": {
              "kind": "none"
            }
          },
          "swap": {
            "type": "swap",
            "size": "2G",
            "bootable": false,
            "content": {
              "kind": "swap",
              "priority": 0,
              "discardPolicy": ""
            }
          },
          "var": {
            "type": "linux",
            "size": "4G",
            "bootable": false,
            "content": {
              "kind": "filesystem",
              "format": "ext4",
              "mountpoint": "/var",
              "mountOptions": ["defaults"],
              "label": "reproos-var",
              "subvols": []
            }
          },
          "home": {
            "type": "linux",
            "size": "100%",
            "bootable": false,
            "content": {
              "kind": "filesystem",
              "format": "ext4",
              "mountpoint": "/home",
              "mountOptions": ["defaults"],
              "label": "reproos-home",
              "subvols": []
            }
          }
        }
      }
    },
    "pools": []
  }
}
)REPROOS_LAYOUT",
        /* hardwareTemplate */
        R"REPROOS_LAYOUT(# /etc/repro/hardware.nim --- generated by the ReproOS installer
import repro_profile

hardware "@REPROOS_ID@":
  cpu:
    arch: "x86_64"
    microcode: "intel"
  boot:
    loaderDevice: "@REPROOS_DEVICE@"
  disko:
    disks:
      "main":
        device: "@REPROOS_DEVICE@"
        table: "gpt"
        partitions:
          "esp":
            kind: "esp"
            size: "@REPROOS_ESP_MIB@M"
            bootable: true
            content:
              filesystem:
                format: "vfat"
                mountpoint: "/boot"
                mountOptions: @["umask=0077"]
                label: "ESP"
          "root-a":
            kind: "linux"
            size: "4G"
            bootable: false
          "roothash-a":
            kind: "linux"
            size: "64M"
            bootable: false
          "root-b":
            kind: "linux"
            size: "4G"
            bootable: false
          "roothash-b":
            kind: "linux"
            size: "64M"
            bootable: false
          "swap":
            kind: "swap"
            size: "2G"
            bootable: false
            content:
              swap:
                priority: 0
                discardPolicy: ""
          "var":
            kind: "linux"
            size: "4G"
            bootable: false
            content:
              filesystem:
                format: "ext4"
                mountpoint: "/var"
                mountOptions: @["defaults"]
                label: "reproos-var"
          "home":
            kind: "linux"
            size: "100%"
            bootable: false
            content:
              filesystem:
                format: "ext4"
                mountpoint: "/home"
                mountOptions: @["defaults"]
                label: "reproos-home"
)REPROOS_LAYOUT",
    },
};

inline constexpr int DiskLayoutPresetCount =
    sizeof(DiskLayoutPresets) / sizeof(DiskLayoutPresets[0]);

}  // namespace generated
}  // namespace reproos
