// M9.R.18.4 -- InstallerState implementation. The renderSystemNim()
// method synthesises the exact text PRD Sec 3.3 documents from the
// wizard's gathered choices; the Summary screen binds a TextArea to
// the return value so the user sees what gets written verbatim.
//
// M9.R.23.2 / M9.R.23.3 -- adds the disko-emit + install() driver. The
// driver shells out to `repro` (the binary installed by the engine
// pipeline) once per step; the QProcess wrappers serialise stdout +
// stderr into the installLog property the Install screen renders.

#include "installer_state.h"

#include <QtCore/QCoreApplication>
#include <QtCore/QDateTime>
#include <QtCore/QDir>
#include <QtCore/QFile>
#include <QtCore/QFileInfo>
#include <QtCore/QProcess>
#include <QtCore/QProcessEnvironment>
#include <QtCore/QTextStream>

InstallerState::InstallerState(QObject *parent) : QObject(parent) {}

void InstallerState::setHostname(const QString &v) {
    if (m_hostname == v) return;
    m_hostname = v;
    emit hostnameChanged();
}

void InstallerState::setLocale(const QString &v) {
    if (m_locale == v) return;
    m_locale = v;
    emit localeChanged();
}

void InstallerState::setTimezone(const QString &v) {
    if (m_timezone == v) return;
    m_timezone = v;
    emit timezoneChanged();
}

void InstallerState::setKeymap(const QString &v) {
    if (m_keymap == v) return;
    m_keymap = v;
    emit keymapChanged();
}

void InstallerState::setUsername(const QString &v) {
    if (m_username == v) return;
    m_username = v;
    emit usernameChanged();
}

void InstallerState::setFullName(const QString &v) {
    if (m_fullName == v) return;
    m_fullName = v;
    emit fullNameChanged();
}

void InstallerState::setPassword(const QString &v) {
    if (m_password == v) return;
    m_password = v;
    emit passwordChanged();
}

void InstallerState::setIsAdmin(bool v) {
    if (m_isAdmin == v) return;
    m_isAdmin = v;
    emit isAdminChanged();
}

void InstallerState::setDesktopKind(const QString &v) {
    if (m_desktopKind == v) return;
    m_desktopKind = v;
    emit desktopKindChanged();
}

void InstallerState::setActiveActivities(const QStringList &v) {
    if (m_activeActivities == v) return;
    m_activeActivities = v;
    emit activeActivitiesChanged();
}

void InstallerState::setActivitiesTomlPath(const QString &v) {
    if (m_activitiesTomlPath == v) return;
    m_activitiesTomlPath = v;
    emit activitiesTomlPathChanged();
}

void InstallerState::setDryRun(bool v) {
    if (m_dryRun == v) return;
    m_dryRun = v;
    emit dryRunChanged();
}

void InstallerState::setTargetDevice(const QString &v) {
    if (m_targetDevice == v) return;
    m_targetDevice = v;
    emit targetDeviceChanged();
}

void InstallerState::setDiskoPreset(const QString &v) {
    if (m_diskoPreset == v) return;
    m_diskoPreset = v;
    emit diskoPresetChanged();
}

void InstallerState::setDiskPassphrase(const QString &v) {
    if (m_diskPassphrase == v) return;
    m_diskPassphrase = v;
    emit diskPassphraseChanged();
}

void InstallerState::setWipeAcknowledged(bool v) {
    if (m_wipeAcknowledged == v) return;
    m_wipeAcknowledged = v;
    emit wipeAcknowledgedChanged();
}

void InstallerState::setAvailableDisks(const QStringList &v) {
    if (m_availableDisks == v) return;
    m_availableDisks = v;
    emit availableDisksChanged();
}

void InstallerState::toggleActivity(const QString &name) {
    if (m_activeActivities.contains(name)) {
        m_activeActivities.removeAll(name);
    } else {
        m_activeActivities.append(name);
        m_activeActivities.sort();
    }
    emit activeActivitiesChanged();
}

bool InstallerState::hasActivity(const QString &name) const {
    return m_activeActivities.contains(name);
}

// Maps PRD Sec 3.1 desktop choice to the activity-shape `dkPlasma` /
// `dkGnome` / `dkSway` / `dkHyprland` variant kinds the
// ReproOS-Configuration-Architecture document defines.
static QString desktopKindToVariant(const QString &kind) {
    if (kind == "plasma") return "dkPlasma";
    if (kind == "gnome") return "dkGnome";
    if (kind == "sway") return "dkSway";
    if (kind == "hyprland") return "dkHyprland";
    return "dkPlasma";
}

QString InstallerState::renderSystemNim() const {
    // Render the user-facing system.nim per PRD Sec 3.3. The format is
    // pinned by ReproOS-Configuration-Architecture; the
    // `import repro_profile` + `system "<name>":` header is canonical.
    QString out;
    QTextStream s(&out);
    s << "# /etc/repro/system.nim --- generated by the ReproOS installer\n";
    s << "import repro_profile\n\n";
    s << "system \"" << m_hostname << "\":\n";
    s << "  imports:\n";
    s << "    \"./hardware.nim\"\n";
    for (const QString &act : m_activeActivities) {
        s << "    \"modules/activities/" << act << ".nim\"\n";
    }
    s << "    \"modules/de/" << m_desktopKind << ".nim\"\n";
    s << "    \"modules/networking/networkmanager.nim\"\n\n";
    s << "  config:\n";
    s << "    hostname: string = \"" << m_hostname << "\"\n";
    s << "    timezone: string = \"" << m_timezone << "\"\n";
    s << "    locale: string = \"" << m_locale << "\"\n";
    s << "    keymap: string = \"" << m_keymap << "\"\n";
    s << "    activeAtBoot: DesktopKind = " << desktopKindToVariant(m_desktopKind) << "\n";
    s << "    defaultUser: string = \"" << m_username << "\"\n\n";
    s << "  users:\n";
    s << "    \"" << m_username << "\":\n";
    s << "      fullName: \"" << m_fullName << "\"\n";
    s << "      groups: @[";
    s << "\"audio\", \"video\", \"networkmanager\"";
    if (m_isAdmin) s << ", \"wheel\"";
    s << "]\n";
    s << "      homeIntent: import \"./home.nim\"\n";
    return out;
}

// M9.R.23.2 -- render the M9.R.22 disko block matching the chosen
// preset. The "advanced" preset produces a hardware "<id>": block with
// no disko: sub-block + a comment instructing the user to add one
// post-install.
QString InstallerState::renderDiskoNim(const QString &id) const {
    QString out;
    QTextStream s(&out);
    s << "# /etc/repro/hardware.nim --- generated by the ReproOS installer\n";
    s << "import repro_profile\n\n";
    s << "hardware \"" << id << "\":\n";
    s << "  cpu:\n";
    s << "    arch: \"x86_64\"\n";
    s << "    microcode: \"intel\"\n";
    s << "  boot:\n";
    s << "    loaderDevice: \"" << (m_targetDevice.isEmpty()
        ? QStringLiteral("/dev/sda") : m_targetDevice) << "\"\n";

    if (m_diskoPreset == "advanced") {
        s << "  # disko: block omitted -- the user opted for the\n";
        s << "  # advanced layout. Hand-author the disks/pools blocks\n";
        s << "  # via the M9.R.22 macro vocabulary; see\n";
        s << "  # reprobuild-specs/ReproOS-Disko-Port.md for examples.\n";
        return out;
    }

    const QString dev = m_targetDevice.isEmpty()
        ? QStringLiteral("/dev/sda") : m_targetDevice;

    s << "  disko:\n";
    s << "    disks:\n";
    s << "      \"main\":\n";
    s << "        device: \"" << dev << "\"\n";
    s << "        table: gpt\n";
    s << "        partitions:\n";
    s << "          \"esp\":\n";
    s << "            kind: esp\n";
    s << "            size: \"512M\"\n";
    s << "            bootable: true\n";
    s << "            content:\n";
    s << "              filesystem:\n";
    s << "                format: \"vfat\"\n";
    s << "                mountpoint: \"/boot\"\n";
    s << "          \"root\":\n";
    s << "            kind: linux\n";
    s << "            size: \"100%\"\n";
    s << "            content:\n";

    if (m_diskoPreset == "encrypted") {
        // LUKS2 + btrfs subvols. The keyFile = "interactive" signals
        // the M9.R.22b apply driver to consume the passphrase from the
        // CT_DISK_PASSPHRASE env var instead of a key file.
        s << "              encrypted:\n";
        s << "                encryption:\n";
        s << "                  kind: \"luks2\"\n";
        s << "                  keyFile: \"interactive\"\n";
        s << "                  allowDiscards: true\n";
        s << "                inner:\n";
        s << "                  filesystem:\n";
        s << "                    format: \"btrfs\"\n";
        s << "                    mountpoint: \"/\"\n";
        s << "                    subvols:\n";
        s << "                      \"@\":\n";
        s << "                        path: \"/\"\n";
        s << "                      \"@home\":\n";
        s << "                        path: \"/home\"\n";
        s << "                      \"@nix\":\n";
        s << "                        path: \"/nix\"\n";
    } else {
        // simple preset (default): ext4 root.
        s << "              filesystem:\n";
        s << "                format: \"ext4\"\n";
        s << "                mountpoint: \"/\"\n";
        s << "                mountOptions: @[\"noatime\"]\n";
    }
    return out;
}

// M9.R.24.2 -- renderDiskoJson: pre-compute the SystemHardwareSpec
// JSON the disk_apply driver consumes, so the live ISO's installer
// can `repro disk apply --confirm <disko.json>` WITHOUT a Nim
// toolchain (the .nim path goes through `nim r` -- requires nim +
// gcc + libc-dev in the live filesystem, which we deliberately don't
// ship). The output must match libs/repro_profile/.../emit.nim's
// emitSystemHardwareJson for the same SystemHardwareSpec input.
//
// Currently supports the `simple` preset only; encrypted/advanced
// fall through to the .nim path (which still requires Nim).
QString InstallerState::renderDiskoJson(const QString &id) const {
    QString out;
    QTextStream s(&out);
    auto esc = [](const QString &x) {
        QString r;
        for (QChar c : x) {
            if (c == '"' || c == '\\') r += '\\';
            r += c;
        }
        return r;
    };
    const QString dev = m_targetDevice.isEmpty()
        ? QStringLiteral("/dev/vda") : m_targetDevice;
    // Filesystem content node (filesystem kind) -- includes all keys
    // parseContentSpec requires when kind==filesystem.
    auto fsContent = [&](const QString &format, const QString &mountpoint,
                         const QString &mountOpts) {
        QString r;
        r += "{\"kind\":\"filesystem\"";
        r += ",\"format\":\"" + esc(format) + "\"";
        r += ",\"mountpoint\":\"" + esc(mountpoint) + "\"";
        r += ",\"mountOptions\":" + mountOpts;
        r += ",\"label\":\"\"";
        r += ",\"subvols\":[]";
        r += "}";
        return r;
    };
    s << "{";
    s << "\"id\":\"" << esc(id) << "\"";
    s << ",\"cpuArch\":\"x86_64\"";
    s << ",\"cpuMicrocode\":\"intel\"";
    s << ",\"kernelModules\":[]";
    s << ",\"loaderDevice\":\"" << esc(dev) << "\"";
    s << ",\"filesystems\":[]";
    s << ",\"graphicsDrivers\":[]";
    s << ",\"audioCards\":[]";
    if (m_diskoPreset == "simple" || m_diskoPreset.isEmpty()) {
        s << ",\"disko\":{";
        s << "\"disks\":{";
        s << "\"main\":{";
        s << "\"device\":\"" << esc(dev) << "\"";
        s << ",\"type\":\"gpt\"";
        s << ",\"partitions\":{";
        // ESP partition.
        s << "\"esp\":{";
        s << "\"type\":\"esp\"";
        s << ",\"size\":\"512M\"";
        s << ",\"bootable\":true";
        s << ",\"content\":" << fsContent("vfat", "/boot", "[]");
        s << "},";
        // Root partition.
        s << "\"root\":{";
        s << "\"type\":\"linux\"";
        s << ",\"size\":\"100%\"";
        s << ",\"bootable\":false";
        s << ",\"content\":" << fsContent("ext4", "/", "[\"noatime\"]");
        s << "}";
        s << "}";
        s << "}";
        s << "}";
        s << ",\"pools\":[]";
        s << "}";
    }
    s << "}";
    return out;
}

// ---------------------------------------------------------------------
// M9.R.23.2 -- lsblk-driven disk refresh.
// ---------------------------------------------------------------------

void InstallerState::refreshAvailableDisks() {
    QStringList disks;
#ifdef Q_OS_LINUX
    QProcess p;
    // -d: skip partitions/holders, -n: no header, -o: chosen columns,
    // -p: print full /dev/* path (we then strip the prefix for the
    // model so the QML side has both forms).
    p.start("lsblk", {"-d", "-n", "-o", "NAME,SIZE,MODEL,VENDOR"});
    if (!p.waitForStarted(2000)) {
        // lsblk missing -- fall back to a single placeholder so the QML
        // doesn't render an empty combo + the user can still see the
        // wizard works end-to-end on test hosts without util-linux.
        disks << "vda 16G QEMU";
        setAvailableDisks(disks);
        return;
    }
    p.waitForFinished(5000);
    const QString out = QString::fromUtf8(p.readAllStandardOutput());
    for (const QString &lineRaw : out.split('\n')) {
        const QString line = lineRaw.trimmed();
        if (line.isEmpty()) continue;
        // Filter loopback + ram devices; users don't want to install
        // onto loop0 or zram by accident.
        if (line.startsWith("loop") || line.startsWith("ram") ||
            line.startsWith("zram") || line.startsWith("sr"))
            continue;
        disks << line;
    }
#else
    // Non-Linux host (the Windows build of the installer is dev-only;
    // PRD Sec 7.1 pins the runtime to the live ISO + Wayland). Emit a
    // placeholder so the QML still works for screenshots.
    disks << "sda 100G Virtual";
    disks << "sdb 500G Virtual";
#endif
    setAvailableDisks(disks);
}

// ---------------------------------------------------------------------
// M9.R.23.3 -- install() orchestration.
// ---------------------------------------------------------------------

void InstallerState::appendLog(const QString &line) {
    const QString stamp = QDateTime::currentDateTimeUtc()
        .toString("yyyy-MM-dd hh:mm:ss");
    const QString stamped = "[" + stamp + "] " + line;
    m_installLog += stamped + "\n";
    emit installLogChanged();
    // M9.R.23.5 -- when running headless (no QML engine, e.g. via
    // --automated CONFIG_TOML or any caller that didn't bind a Qml
    // engine to installerState), mirror the line to stderr so the
    // operator sees the same trace the GUI would show. The GUI path
    // ignores this duplicate; QML binds to installLogChanged and
    // re-reads installLog every time.
    QTextStream(stderr) << stamped << '\n';
}

void InstallerState::setInstallStatus(const QString &s) {
    if (m_installStatus == s) return;
    m_installStatus = s;
    emit installStatusChanged();
}

void InstallerState::setInstallProgress(qreal v) {
    if (qFuzzyCompare(m_installProgress, v)) return;
    m_installProgress = v;
    emit installProgressChanged();
}

void InstallerState::setInstallRunning(bool v) {
    if (m_installRunning == v) return;
    m_installRunning = v;
    emit installRunningChanged();
}

bool InstallerState::dryRunDestructive() const {
    const QByteArray v =
        qgetenv("REPRO_DISK_DRY_RUN");
    return !v.isEmpty() && v != "0";
}

// Locate the `repro` binary. The live ISO ships it at /usr/bin/repro;
// during dev we honour CT_REPRO_BINARY for an override path.
static QString reproBinary() {
    const QByteArray env = qgetenv("CT_REPRO_BINARY");
    if (!env.isEmpty()) return QString::fromUtf8(env);
    if (QFileInfo::exists("/usr/bin/repro")) return "/usr/bin/repro";
    // Fall back to PATH lookup -- QProcess does this automatically when
    // the program string has no directory separator.
    return "repro";
}

int InstallerState::runReproSubcommand(const QStringList &args,
                                        int timeoutMs) {
    QProcess p;
    p.setProcessChannelMode(QProcess::MergedChannels);
    const QString bin = reproBinary();
    appendLog(QString("$ %1 %2").arg(bin, args.join(' ')));
    p.start(bin, args);
    if (!p.waitForStarted(5000)) {
        appendLog(QString("spawn failed: %1").arg(p.errorString()));
        return -1;
    }
    if (!p.waitForFinished(timeoutMs)) {
        p.kill();
        appendLog(QString("timeout after %1ms").arg(timeoutMs));
        return -2;
    }
    const QString output = QString::fromUtf8(p.readAllStandardOutput());
    for (const QString &line : output.split('\n')) {
        if (!line.isEmpty()) appendLog("  " + line);
    }
    return p.exitCode();
}

bool InstallerState::runReproHardwareProbe(const QString &outputPath) {
    // `repro hardware probe --output <path> --regenerate` writes the
    // probed hardware.nim. The wizard later overlays the disko block on
    // top by composing the rendered text directly.
    QStringList args = {"hardware", "probe", "--output", outputPath,
                        "--regenerate"};
    return runReproSubcommand(args) == 0;
}

bool InstallerState::runReproDiskApply() {
    if (dryRunDestructive()) {
        appendLog("[dry-run] would shell out to `repro disk apply "
                  "--confirm`");
        return true;
    }
    // The wizard writes the disko block to a temp file, then runs
    // `repro disk apply <tmp> --confirm`. The temp file lives under
    // /tmp/repro-installer-<pid>/ + is cleaned up by the OS reboot.
    const QString tmpDir = QString("/tmp/repro-installer-%1")
        .arg(QCoreApplication::applicationPid());
    QDir().mkpath(tmpDir);
    // M9.R.24.2 -- write the JSON form so `repro disk apply` skips
    // the `nim r` compile step (the live ISO doesn't bundle Nim).
    const QString diskoPath = tmpDir + "/disko.json";
    writeFileAtomic(diskoPath, renderDiskoJson());
    QStringList args = {"disk", "apply", diskoPath, "--confirm"};
    if (!m_targetDevice.isEmpty()) {
        args << "--device" << m_targetDevice;
    }
    return runReproSubcommand(args, 600000) == 0;
}

bool InstallerState::runReproDiskMount(const QString &mountPoint) {
    if (dryRunDestructive()) {
        appendLog(QString("[dry-run] would mount disko layout at %1")
                  .arg(mountPoint));
        return true;
    }
    const QString tmpDir = QString("/tmp/repro-installer-%1")
        .arg(QCoreApplication::applicationPid());
    const QString diskoPath = tmpDir + "/disko.json";
    if (!QFileInfo::exists(diskoPath)) {
        writeFileAtomic(diskoPath, renderDiskoJson());
    }
    QStringList args = {"disk", "mount", diskoPath, "--target", mountPoint,
                        "--confirm"};
    return runReproSubcommand(args) == 0;
}

bool InstallerState::runReproDiskUnmount(const QString &mountPoint) {
    if (dryRunDestructive()) {
        appendLog(QString("[dry-run] would unmount %1").arg(mountPoint));
        return true;
    }
    const QString tmpDir = QString("/tmp/repro-installer-%1")
        .arg(QCoreApplication::applicationPid());
    const QString diskoPath = tmpDir + "/disko.json";
    QStringList args = {"disk", "unmount", diskoPath, "--target",
                        mountPoint};
    return runReproSubcommand(args) == 0;
}

bool InstallerState::runReproSystemApply(const QString &target) {
    if (dryRunDestructive()) {
        appendLog(QString("[dry-run] would run `repro infra install-root "
                          "--target %1 --device %2`")
                  .arg(target,
                       m_targetDevice.isEmpty() ? QStringLiteral("/dev/vda")
                                                : m_targetDevice));
        return true;
    }
    // M9.R.41: install-time root-mirror.  The previous
    // ``runReproSystemApply`` path called ``repro infra apply
    // --target`` which the dispatcher never accepted (apply is a
    // system-profile reconciliation, not a root-mirror); the
    // ``runMinimalBootstrap`` fallback only copied kernel + initrd +
    // GRUB and left the rest of /mnt empty.  ``repro infra
    // install-root`` is the install-time analogue: rsync -aHAX the
    // live root onto /mnt, generate fstab from the disko spec Phase
    // 4 wrote to <target>/etc/repro/hardware.nim, then install GRUB
    // + write the target-side grub.cfg.  See M9.R.41.1 commit body.
    const QString grubDevice = m_targetDevice.isEmpty()
        ? QStringLiteral("/dev/vda") : m_targetDevice;
    const QString hn = m_hostname.isEmpty()
        ? QStringLiteral("reproos-vm") : m_hostname;
    // M9.R.41: point install-root at the JSON form of the disko spec
    // the Phase 2 disk-apply step already wrote to /tmp/repro-
    // installer-<pid>/disko.json (via writeFileAtomic +
    // renderDiskoJson).  The Phase 4 /mnt/etc/repro/hardware.nim
    // file is a Nim SOURCE file; loading it via `loadDiskoFromSource`
    // requires ``nim r`` which is NOT bundled on the live ISO (the
    // M9.R.24.2 commit body documented this), so we pass --disko
    // explicitly at the JSON path.
    const QString tmpDir = QString("/tmp/repro-installer-%1")
        .arg(QCoreApplication::applicationPid());
    const QString diskoJson = tmpDir + "/disko.json";
    if (!QFileInfo::exists(diskoJson)) {
        writeFileAtomic(diskoJson, renderDiskoJson());
    }
    QStringList args = {"infra", "install-root",
                        "--target", target,
                        "--source", "/",
                        "--device", grubDevice,
                        "--hostname", hn,
                        "--disko", diskoJson};
    // M9.R.44b: cap bumped from 30 min -> 3 hr.  The original 30 min
    // was sized for an SSD host with KVM passthrough; on the eli-wsl
    // host (Windows -> WSL2 -> QEMU triple-virt, no KVM) Phase 5 rsync
    // runs at ~0.8 MB/s and the from-source live root closure is ~3 GB
    // by M9.R.44, putting Phase 5 wall at 60-90 min.  The 30 min cap
    // killed Phase 5 mid-rsync in the M9.R.42/M9.R.43/M9.R.44b runs;
    // installer reported Phase 5 FAILED while the orphaned rsync child
    // continued silently in the background for another hour.  3 hr
    // covers the slow path with headroom and is still finite enough to
    // surface a genuine wedge.
    return runReproSubcommand(args, 10800000) == 0;
}

void InstallerState::writeFileAtomic(const QString &path,
                                      const QString &text) {
    const QFileInfo fi(path);
    QDir().mkpath(fi.absolutePath());
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        appendLog(QString("write %1 failed: %2").arg(path, f.errorString()));
        return;
    }
    f.write(text.toUtf8());
    f.close();
    appendLog(QString("wrote %1 (%2 bytes)").arg(path)
              .arg(text.toUtf8().size()));
}

// M9.R.41: ``runMinimalBootstrap`` is DELETED.  The previous M9.R.24
// stub fell through to a kernel+initrd+GRUB-only path when ``repro
// infra apply --target`` failed (which it always did — the subcommand
// never accepted --target).  ``repro infra install-root`` is the real
// implementation; on failure the installer now aborts with an explicit
// error rather than silently producing an unbootable disk.

void InstallerState::install() {
    if (m_installRunning) {
        appendLog("install() called while already running -- ignored");
        return;
    }
    setInstallRunning(true);
    m_installLog.clear();
    emit installLogChanged();
    setInstallProgress(0.0);
    setInstallStatus("Starting install");

    const QString target = QStringLiteral("/mnt");
    const QString sysNimPath = target + "/etc/repro/system.nim";
    const QString hwNimPath = target + "/etc/repro/hardware.nim";

    appendLog("Phase 1: probing hardware...");
    setInstallStatus("Probing target hardware");
    setInstallProgress(0.1);
    const QString probeOutput = QString("/tmp/repro-installer-%1/probed-hardware.nim")
        .arg(QCoreApplication::applicationPid());
    if (!runReproHardwareProbe(probeOutput)) {
        appendLog("hardware probe failed");
        setInstallRunning(false);
        emit installFailed("hardware probe failed");
        return;
    }

    appendLog("Phase 2: applying disk layout...");
    setInstallStatus("Applying disk layout");
    setInstallProgress(0.3);
    if (!runReproDiskApply()) {
        appendLog("disk apply failed");
        setInstallRunning(false);
        emit installFailed("disk apply failed");
        return;
    }

    appendLog("Phase 3: mounting target rootfs at " + target);
    setInstallStatus("Mounting target");
    setInstallProgress(0.45);
    if (!runReproDiskMount(target)) {
        appendLog("disk mount failed");
        setInstallRunning(false);
        emit installFailed("disk mount failed");
        return;
    }

    appendLog("Phase 4: writing /etc/repro/{system,hardware}.nim");
    setInstallStatus("Writing system + hardware Nim files");
    setInstallProgress(0.55);
    if (!dryRunDestructive()) {
        writeFileAtomic(sysNimPath, renderSystemNim());
        writeFileAtomic(hwNimPath, renderDiskoNim());
    } else {
        appendLog(QString("[dry-run] would write %1").arg(sysNimPath));
        appendLog(QString("[dry-run] would write %1").arg(hwNimPath));
    }

    appendLog("Phase 5: applying system profile...");
    setInstallStatus("Applying system profile");
    setInstallProgress(0.7);
    if (!runReproSystemApply(target)) {
        // M9.R.41: ``repro infra install-root`` failed.  This is now
        // a hard error — the M9.R.24 stub's "minimal bootstrap"
        // fallback intentionally left the installed disk without a
        // real rootfs, blocking G3 (boot installed) + G4 (DE smoke).
        // The campaign close-out makes Phase 5 the SOURCE OF TRUTH
        // for the installed system's contents; a failure here means
        // the install is broken and the user must investigate, not
        // silently proceed with a half-formed system.
        appendLog("Phase 5 FAILED: `repro infra install-root` did "
                  "not complete; aborting install (the previous "
                  "M9.R.24 minimal-bootstrap fallback is removed in "
                  "M9.R.41 — a failed install must surface, not "
                  "silently produce an unbootable disk).");
        setInstallRunning(false);
        emit installFailed("system root-mirror failed");
        return;
    }

    appendLog("Phase 6: unmounting target...");
    setInstallStatus("Unmounting");
    setInstallProgress(0.95);
    runReproDiskUnmount(target);

    setInstallProgress(1.0);
    setInstallStatus("Install complete");
    appendLog("install complete");
    setInstallRunning(false);
    emit installComplete();
}

// ---------------------------------------------------------------------
// M9.R.23.5 -- automated config loader. Reads a minimal key=value TOML
// (no nested tables -- this is the smoke-harness path) + drives the
// install() sequence directly.
// ---------------------------------------------------------------------

int InstallerState::runAutomatedConfig(const QString &configPath) {
    QFile f(configPath);
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text)) {
        appendLog(QString("automated: cannot open %1: %2")
                  .arg(configPath, f.errorString()));
        return 1;
    }
    QTextStream in(&f);
    while (!in.atEnd()) {
        const QString lineRaw = in.readLine();
        const QString line = lineRaw.trimmed();
        if (line.isEmpty() || line.startsWith('#')) continue;
        const int eq = line.indexOf('=');
        if (eq < 0) continue;
        const QString key = line.left(eq).trimmed();
        QString value = line.mid(eq + 1).trimmed();
        // Strip surrounding double quotes if present.
        if (value.length() >= 2 && value.startsWith('"') &&
            value.endsWith('"')) {
            value = value.mid(1, value.length() - 2);
        }
        if (key == "hostname") setHostname(value);
        else if (key == "locale") setLocale(value);
        else if (key == "timezone") setTimezone(value);
        else if (key == "keymap") setKeymap(value);
        else if (key == "username") setUsername(value);
        else if (key == "fullName") setFullName(value);
        else if (key == "password") setPassword(value);
        else if (key == "desktopKind") setDesktopKind(value);
        else if (key == "targetDevice") setTargetDevice(value);
        else if (key == "diskoPreset") setDiskoPreset(value);
        else if (key == "diskPassphrase") setDiskPassphrase(value);
        else if (key == "isAdmin") setIsAdmin(value == "true");
        else if (key == "wipeAcknowledged") setWipeAcknowledged(value == "true");
    }
    // Force the wipe acknowledgement on -- the operator typed the
    // config file by hand, so they already opted in.
    setWipeAcknowledged(true);
    // Track failure via a one-shot signal hook so the return code
    // reflects what actually happened. install() runs synchronously
    // because every helper uses QProcess::waitForFinished.
    bool failed = false;
    QString failureReason;
    auto conn = connect(this, &InstallerState::installFailed, this,
        [&](const QString &reason) {
            failed = true;
            failureReason = reason;
        });
    install();
    disconnect(conn);
    if (failed) {
        QTextStream(stderr) << "install failed: " << failureReason << '\n';
        return 1;
    }
    if (m_installProgress < 1.0) {
        QTextStream(stderr) << "install incomplete (progress=" <<
            m_installProgress << ")\n";
        return 1;
    }
    return 0;
}
