font pango:monospace 12
swaybg_command -
for_window [title="ReproOS Desktop"] border none
exec /usr/bin/busybox env QT_PLUGIN_PATH=/opt/repro/reprobuild-packages/packages/source/qt6-base/.repro/output/install/usr/plugins:/opt/repro/reprobuild-packages/packages/source/qt6-wayland/.repro/output/install/usr/plugins QML_IMPORT_PATH=/opt/repro/reprobuild-packages/packages/source/qt6-declarative/.repro/output/install/usr/qml /usr/bin/qml -platform wayland /usr/share/reproos/reproos-desktop.qml
