// M9.R.18.12 -- Finished screen. Per ReproOS-Installer-PRD.md Sec 3.1
// screen 10 the final screen prompts the user to reboot into the
// installed system. v0.1 surfaces the "Reboot" button (wired to Qt.quit
// by main.qml's Next handler); M9.R.19 wires it to systemctl reboot via
// the M82 broker.

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

Item {
    ColumnLayout {
        anchors.centerIn: parent
        spacing: 28
        width: 540

        Label {
            text: qsTr("Installation complete")
            font.pixelSize: 32
            font.weight: Font.Light
            color: "#e6e6f0"
            Layout.alignment: Qt.AlignHCenter
        }

        Label {
            text: qsTr(
                "ReproOS has been written to your target disk. Remove the install "
                + "medium and click Reboot to start your new system.")
            font.pixelSize: 14
            color: "#b8b8d0"
            wrapMode: Text.WordWrap
            horizontalAlignment: Text.AlignHCenter
            Layout.fillWidth: true
        }

        Rectangle {
            Layout.fillWidth: true
            Layout.preferredHeight: 1
            color: "#2c2c3a"
            Layout.topMargin: 8
            Layout.bottomMargin: 8
        }

        Label {
            text: qsTr("What lives on disk:")
            font.pixelSize: 13
            font.weight: Font.Medium
            color: "#e6e6f0"
        }

        Label {
            text: qsTr(
                "  - /etc/repro/system.nim    (the configuration you reviewed)\n"
                + "  - /etc/repro/hardware.nim  (auto-generated by `repro hardware probe`)\n"
                + "  - /etc/repro/modules/...   (the activity modules you selected)\n"
                + "  - /etc/repro/home/<user>.nim (your user's home-intent stub)")
            font.family: "monospace"
            font.pixelSize: 11
            color: "#a0a0b8"
        }

        Label {
            Layout.topMargin: 16
            text: qsTr(
                "Edit any of those files and run `repro infra apply` to roll the "
                + "system forward. Rollback is `repro infra rollback` -- atomic, "
                + "per-generation, NixOS-shape.")
            font.pixelSize: 12
            color: "#8a8aa3"
            wrapMode: Text.WordWrap
            horizontalAlignment: Text.AlignHCenter
            Layout.fillWidth: true
        }
    }
}
