# /etc/repro/hardware.nim --- generated by the ReproOS installer
import repro_profile

hardware "INSTALL":
  cpu:
    arch: "x86_64"
    microcode: "intel"
  boot:
    loaderDevice: "/dev/vda"
  disko:
    disks:
      "main":
        device: "/dev/vda"
        table: gpt
        partitions:
          "esp":
            kind: esp
            size: "512M"
            bootable: true
            content:
              filesystem:
                format: "vfat"
                mountpoint: "/boot"
          "root":
            kind: linux
            size: "100%"
            content:
              filesystem:
                format: "ext4"
                mountpoint: "/"
                mountOptions: @["noatime"]
