# /etc/repro/system.nim --- generated by the ReproOS installer
import repro_profile

system "reproos-smoke":
  imports:
    "./hardware.nim"
    "modules/de/sway.nim"
    "modules/networking/networkmanager.nim"

  config:
    hostname: string = "reproos-smoke"
    timezone: string = "UTC"
    locale: string = "en_US.UTF-8"
    keymap: string = "us"
    activeAtBoot: DesktopKind = dkSway
    defaultUser: string = "repro"

  users:
    "repro":
      fullName: "Repro Test User"
      groups: @["audio", "video", "networkmanager", "wheel"]
      homeIntent: import "./home.nim"
